### ISSUE TITLE
General error: 3064 Incorrect type for argument geojson in function st_asgeojson. The SQL being executed was: SELECT ST_asGeoJson('***') as polygon

### ISSUE THREAD

**Issue by avilgunic** [nanson/yii2-postgis#2]
Hi, I'm receiving the error when retrieving record:

> SQLSTATE[HY000]: General error: 3064 Incorrect type for argument geojson in function st_asgeojson.
> The SQL being executed was: SELECT ST_asGeoJson('�������H@�i�7@W [�H@�����7@�#�p�H@a�B�7@�4��M�H@~Ч�7@�Ņ�H@�����7@������H@�i�7@') as polygon

After changing the line of code:
`$res = $query->select("ST_asGeoJson('" . $this->owner->$attribute . "') as $attribute")->createCommand()->queryOne();`
to the
`$res = $query->select("ST_asGeoJson($attribute) as $attribute")->from($this->owner->tableName())->where(["id"=>$this->owner->id])->createCommand()->queryOne();`
It works!

So seems incorrect data are passed into ST_asGeoJson, but why?

DB field type was POLYGON, now GEOMETRY, changing did not help.

**Comment by thedenische** [comment]
SQL must looks something like this:

``` SQL
ST_asGeoJson('0101000020E61000005F69CF1BDD0842404521133AF97B4A40') as polygon
```

Method GeometryBehavior->postgisToGeoJson() called afterFind model for converting Postgis binary format to GeoJson.

In my case, I directly use value of model attribute, e.g:

``` php
echo ($this->owner->$attribute) // 0101000020E61000005F69CF1BDD0842404521133AF97B4A40
```

In second variant - you getting row from DB by id one more time, and use value from there. 

Looks like another behavior change value of model attribute.

**Comment by avilgunic** [comment]
I have no other behaviors. I've changed this code, to prevent errors during development. So I need to change it back to prevent a lot of queries.

When just doing SELECT ST_GeomFromGeoJSON MySQL returns value which is not like your example 0101000020.......B4A40

> SELECT ST_GeomFromGeoJSON('{"type":"Point",
>                           "coordinates":[59.816194721748,33.977360725403],
>                           "crs":{"type":"name","properties":{"name":"EPSG:4326"}}}')

MySQL Workbench query screenshot - [http://prntscr.com/bzz0v4](http://prntscr.com/bzz0v4)

So the same data it writes to the DB and the same it tries to include into ST_asGeoJson query, I'm trying different data types, but I'm getting the same result. Which data type do you use?

So What difference can be between our environment which affects this difference in queries?

I'm using ubuntu 14.04 MySQL 5.7

P.S.
When running:

> SELECT ST_asGeoJson('0101000020E61000005F69CF1BDD0842404521133AF97B4A40') as polygon

MySQL returns  #3064 - Incorrect type for argument geojson in function st_asgeojson.

**Comment by thedenische** [comment]
My extension for Postgis - spatial extension for Postgresql. I don't tried to use it with MySQL.
As I know, Postgis uses own binary format.
If your variant, with getting field as geoJson directly from DB works fine, you can use [PostgisQueryTrait](https://github.com/nanson/yii2-postgis#postgisquerytrait).
It will be substitute `ST_asGeoJson("geo_field_name")` automatically, when you getting models from DB.
